#!/usr/bin/env python3
"""Regenerate VS Code IntelliSense config for the U-Boot tree.

Reads build/include/generated/autoconf.h (produced by Kconfig during
`make O=build mt7621_rfb_defconfig`) and writes .vscode/c_cpp_properties.json
with the CONFIG_* defines plus the include path for this MT7621 (MIPS) tree.

Run it again after changing the defconfig or running menuconfig:
    python3 .vscode/update_defines.py
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent          # U-Boot source root
AUTOCONF = ROOT / "build" / "include" / "generated" / "autoconf.h"
OUT = Path(__file__).resolve().parent / "c_cpp_properties.json"

# Mirrors the -I flags the real build passes (see Makefile KBUILD_CPPFLAGS):
#   -I$(srctree)/include -I$(objtree)/include -I$(srctree)/arch/mips/include
#   -I$(srctree)/arch/mips/mach-mtmips/include -I$(srctree)/dts/upstream/include
INCLUDE_PATH = [
    # main U-Boot headers: <linux/...>, <configs/...>, <dt-bindings/...>, ...
    "${workspaceFolder}/include",
    "${workspaceFolder}/include/asm-generic",
    "${workspaceFolder}/include/configs",
    # arch-specific headers: <asm/...> resolves to arch/mips/include/asm
    "${workspaceFolder}/arch/mips/include",
    "${workspaceFolder}/arch/mips/mach-mtmips/include",
    # board directory referenced by CFG_BOARDDIR in build/include/config.h
    "${workspaceFolder}/board/mediatek/mt7621",
    # device-tree bindings (dtc include path, Makefile: -I$(srctree)/dts/upstream/include)
    "${workspaceFolder}/dts/upstream/include",
    # generated headers: config.h, autoconf.h, version_autogenerated.h, ...
    "${workspaceFolder}/build/include",
    "${workspaceFolder}/build/include/generated",
]

# Always-on build flags (Makefile: KBUILD_CPPFLAGS := -D__KERNEL__ -D__UBOOT__);
# without them IntelliSense takes the host/kernel branches of #ifndef __UBOOT__
# and reports bogus missing headers.
BUILD_DEFINES = ["__KERNEL__", "__UBOOT__"]

# The build force-includes linux/kconfig.h into every TU (-include in
# KBUILD_CPPFLAGS); this provides CONFIG_IS_ENABLED(), CONFIG_VAL(), etc.
FORCED_INCLUDE = ["${workspaceFolder}/include/linux/kconfig.h"]

# Tag-parser roots so "Go to Definition" works across .c files too
# (limitSymbolsToIncludedHeaders: false => index all files under these paths).
BROWSE_PATH = INCLUDE_PATH + [
    "${workspaceFolder}/common",
    "${workspaceFolder}/cmd",
    "${workspaceFolder}/drivers",
    "${workspaceFolder}/lib",
    "${workspaceFolder}/net",
    "${workspaceFolder}/env",
    "${workspaceFolder}/fs",
    "${workspaceFolder}/boot",
    "${workspaceFolder}/disk",
    "${workspaceFolder}/api",
    "${workspaceFolder}/arch/mips",
    "${workspaceFolder}/board/mediatek",
]


def parse_defines(path):
    defines = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = re.sub(r"/\*.*$", "", line).strip()  # drop trailing comments
        m = re.match(r"#\s*define\s+([A-Za-z_][A-Za-z0-9_]*)(?:\s+(.*))?$", line)
        if not m:
            continue
        name, value = m.group(1), (m.group(2) or "").strip()
        if not value:
            defines.append(name)
        elif re.fullmatch(r'"(?:[^"\\]|\\.)*"', value):
            defines.append(f"{name}={value}")       # keep string quoting
        else:
            defines.append(f"{name}={value}")
    return defines


def main():
    if not AUTOCONF.exists():
        sys.exit(
            f"error: {AUTOCONF} not found\n"
            "Build the defconfig first, e.g.:\n"
            "    make O=build mt7621_rfb_defconfig"
        )
    defines = parse_defines(AUTOCONF)
    if not defines:
        sys.exit(f"error: no #define entries found in {AUTOCONF}")

    config = {
        "configurations": [
            {
                "name": "U-Boot (MT7621)",
                "includePath": INCLUDE_PATH,
                "defines": BUILD_DEFINES + defines,
                "forcedInclude": FORCED_INCLUDE,
                "compilerPath": "/usr/bin/clang",
                "cStandard": "c17",
                "cppStandard": "c++14",
                "intelliSenseMode": "linux-clang-x64",
                "browse": {
                    "path": BROWSE_PATH,
                    "limitSymbolsToIncludedHeaders": False,
                },
            }
        ],
        "version": 4,
    }
    OUT.write_text(json.dumps(config, indent=4) + "\n", encoding="utf-8")
    print(f"wrote {OUT}  ({len(defines)} defines)")


if __name__ == "__main__":
    main()
